"use client";

import React from "react";
import {
  Flame,
  Zap,
  Award,
  Trophy,
  CheckCircle2,
  Check,
  X,
  Volume2,
  AudioWaveform,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  Lock,
  LockOpen,
  Heart,
  HeartCrack,
  Timer,
  Clock,
  Gamepad2,
  Settings,
  SlidersHorizontal,
  User,
  Home,
  BookOpen,
  Book,
  Landmark,
  Palette,
  Shirt,
  BadgeCheck,
  Star,
  Sparkles,
  MapPin,
  Play,
  RotateCcw,
  VolumeX,
  Compass,
  Share2,
  Info,
  ShieldAlert,
  Search,
  ChevronRight,
  ChevronDown,
  Bell,
  Radio,
  RadioTower,
  Eye,
  EyeOff,
  PlusCircle,
  AlertTriangle,
  BookmarkPlus,
  History,
  GraduationCap,
  type LucideProps,
} from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Gamification & Badges
  local_fire_department: Flame,
  bolt: Zap,
  stars: Sparkles,
  star: Star,
  military_tech: Award,
  workspace_premium: Trophy,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  favorite: Heart,
  heart_broken: HeartCrack,

  // Learning & Culture
  auto_stories: BookOpen,
  menu_book: Book,
  school: GraduationCap,
  temple_buddhist: Landmark,
  account_balance: Landmark,
  palette: Palette,
  apparel: Shirt,
  dry_cleaning: Shirt,
  styler: Shirt,
  checkroom: Shirt,
  hub: Sparkles,
  explore: Compass,
  conversion_path: Compass,

  // Audio & Media
  volume_up: Volume2,
  volume_off: VolumeX,
  graphic_eq: AudioWaveform,
  play_arrow: Play,
  play_circle: Play,
  record_voice_over: Volume2,
  music_note: AudioWaveform,

  // Actions & Navigation
  close: X,
  check: Check,
  check_circle: CheckCircle2,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  arrow_right_alt: ArrowRight,
  east: ArrowRight,
  keyboard_arrow_up: ArrowUp,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  north_east: ArrowRight,
  home: Home,
  person: User,
  settings: Settings,
  tune: SlidersHorizontal,
  share: Share2,
  refresh: RotateCcw,
  replay: RotateCcw,

  // Status & Utility
  lock: Lock,
  lock_open: LockOpen,
  timer: Timer,
  schedule: Clock,
  sports_esports: Gamepad2,
  info: Info,
  warning: AlertTriangle,
  location_on: MapPin,
  map: MapPin,
  notifications_active: Bell,
  search: Search,
  add_circle: PlusCircle,
  bookmark_add: BookmarkPlus,
  history_edu: History,
  family_history: Landmark,
  radio_button_checked: Radio,
  radio_button_unchecked: RadioTower,
  visibility: Eye,
  visibility_off: EyeOff,
  shield_person: ShieldAlert,
  policy: ShieldAlert,
  hourglass_top: Timer,
  quick_reference: BookOpen,
  sentiment_very_dissatisfied: HeartCrack,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

export function DynamicIcon({ name, ...props }: DynamicIconProps) {
  const IconComponent = ICON_MAP[name] || Sparkles;
  return <IconComponent {...props} />;
}
